
BUILD_DIR=build\vc
BUILDFLAG=$(BUILD_DIR)\buildflag
DOXYGEN=doxygen.exe

DOXYGEN_INPUT = \
	pages\*.dox \
	pages_auto\*.dox

ALL : $(BUILDFLAG)
	
$(BUILD_DIR) :
    if not exist $(BUILD_DIR) mkdir $(BUILD_DIR)

$(BUILDFLAG) : $(BUILD_DIR) $(DOXYGEN_INPUT) Doxyfile
	$(DOXYGEN) Doxyfile
	echo flagged > $@

CLEAN :
	-@ if EXIST $(BUILD_DIR)\* del /f /q $(BUILD_DIR)\*
    -@ if EXIST html rmdir /s /q html

